config/routes.rb
Rails.application.routes.draw do
  #サインアウトできなかったので追加した
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users, :controllers => {
    :registrations => "registrations"
  }
  resources :users, only: [:show, :index, :destroy]
  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'

  match '/about', to: 'static_pages#about', via: 'get'

  match '/contact', to: 'static_pages#contact', via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  #記事からユーザーへ１対１の関連付け
  belongs_to :user
  #default_scopeを使って記事の表示順を最新順に変更（降順）
  default_scope -> { order('created_at DESC')}


#バリデーション設定
  #記事を保存するためにはcontent(内容)が空だと保存不可、更に140文字以上はダメです
  validates :content, presence: true, length: { maximum: 140 }
  #記事を保存するためにはuser_idを持っていないと保存出来ない
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #name情報が必須でnameが無いと保存できない + 最大50文字まで
  validates :name, presence: true, length: {maximum: 50}

  #Micropost（記事）と１対多の関係
  has_many :microposts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  #リダイレクト先をユーザーページにする
  def after_sign_up_path_for(resource)
      user_path(resource)
  end

  private
  #strong paramaters
    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_passeord)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #showのみをサインインなしで閲覧可能にする(indexは閲覧にサインインが必要)
  before_action :authenticate_user!, :except=>[:show]
  #削除はサインインしたadminユーザーしか出来ない
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end


  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  private
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Ruby on Rails Sample App"
      if page_title.empty?
          base_title
        else
           "#{page_title}"
      end
  end

#flashメッセージの装飾に命令を追加
  def bootstrap_class_for(flash_type)
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 })
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class = "footer" >
  <small>
    <a href="http://railstutorial.org/">Rails Tutrial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--CSSのnavbar系のクラスはBootstrapで特定の挙動が設定されている-->
<!--navbar: ナビゲーションバーに付ける基本スタイル -->
<!--navbar-fixed-top: 上部固定 -->
<!--navbar-inverse: 色指定 -->
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>

<!--bootstrapのドロップダウン機能を使うための命令-->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
         </script>
</header>

app/views/layouts/_shiv.html.erb
<!--[if lt IE9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render '/layouts/shiv'%>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class = "container">

      <% flash.each do |key, value| %>
        <div class="alert <%= bootstrap_class_for(key) %>"><%= value %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <!-- debug: 開発環境のみで表示する -->
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>


</html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/shared/_error_messages.html.erb
<!--オブジェクトが空白の場合（エラーが合った場合の処理）-->
<% if object.errors.any? %>
  <div id="error_explanation"><!--CSS id-->
      <div class="alert alert-danger">
          The form contains <%= pluralize(object.errors.count, "error")%>
      </div>
      <ul>
        <!--エラーメッセージがmsgに代入されて表示される-->
        <% object.errors.full_messages.each do |msg| %>
          <li> <%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide(:title, 'About')%>
<h1>About Us</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
Contact Rails
<a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<%= provide(:title, 'Help') %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Sample App</h1>
    <p>
      Rails Sample
    </p>

    <%= link_to "Sigin up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/', class: "image1" %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52%>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !(current_user == user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1> All Users </h1>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<!--ブラウザのタイトルに名前表示-->
<% provide(:title, @user.name) %>

<!--内容-->
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %></br>
        <%= @user.email %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
      <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts, renderer: BootstrapPagination::Rails %>
      <% end %>
  </div>
</div>